Feature/first elasticsearch requests
humlib/humlib-be pull request #38
Opened 2022-03-25 19:47 UTC by ninjeanne

2022-03-26 07:07 UTC, mor4thii requested changes

2022-03-26 07:07 UTC, mor4thii commented on src/main/kotlin/com/humlib/controller/HumansController.kt
> +    val humanProfileRepository: HumanProfileRepository
Wir sollten eine Serviceschicht einziehen. Oder, anders gesagt, eine Schicht, die sich mit der Fachlichkeit beschäftigt. Die ist dann auch zu testen.

2022-03-26 07:07 UTC, mor4thii commented on src/main/kotlin/com/humlib/controller/HumansController.kt
> +    fun getHuman(@PathVariable id: UUID, authentication: Authentication): HumanProfile {
HumanProfile = Human? Wie ist das in der Fachlichkeit? Wollen wir hier "DTOs" ans FE übergeben, um unsere Fachlichkeit unabhängig von der "Präsentation" (also in dem Falle der API) zu machen?

2022-03-26 07:07 UTC, mor4thii commented on src/main/kotlin/com/humlib/controller/SearchHumansController.kt
> +    val humanProfileRepository: HumanProfileRepository
Auch hier: Serviceschicht.

2022-03-26 07:07 UTC, mor4thii commented on src/main/kotlin/com/humlib/controller/SearchHumansController.kt
> +    ): List<HumanProfile> {
Dieser und der nächset Block sind ja, bis auf die Anzahl der zu matchenden tags, doppelt. Könnte man ja in eine Methode (im Service) auslagern.

2022-03-26 07:07 UTC, mor4thii commented on src/main/kotlin/com/humlib/model/HumanProfile.kt
> +data class HumanProfile(
Einfach nur "Human" ? Und das ist ja unser Domänenobjekt, oder?

2022-03-26 07:07 UTC, mor4thii commented on src/main/kotlin/com/humlib/model/HumanProfileTags.kt
> +class HumanProfileTags(
Reicht "tags"?

2022-03-26 07:07 UTC, mor4thii commented on src/main/kotlin/com/humlib/model/HumanProfileTags.kt
> +    var tags: List<String>,
Das kann val sein. List ist eh auch immutable in Kotlin.

2022-03-26 07:07 UTC, mor4thii commented on src/main/kotlin/com/humlib/model/HumanProfile.kt
> +    var tags: List<String>,
val?

2022-03-26 07:07 UTC, mor4thii commented on src/main/kotlin/com/humlib/model/User.kt
> +
Da ist wirklich ein Umbruch zu viel.

2022-03-26 07:07 UTC, mor4thii commented on src/main/resources/application.yaml
> +elasticsearch:
Das sollte eher in die application-local.yaml, oder?

2022-03-26 07:07 UTC, mor4thii commented on src/test/kotlin/com/humlib/HumLibBackendApplicationTests.kt
> +//	@ClassRule
Das kann noch weg

2022-03-26 07:07 UTC, mor4thii commented on pom.xml
> +        <!--
Das kann noch weg

2022-03-26 15:32 UTC, ninjeanne commented on docker/elasticstack/docker-compose.yml
>        bash -c '
welche zips?

2022-03-26 15:34 UTC, ninjeanne commented on src/main/kotlin/com/humlib/config/RestClientConfig.kt
> +
ich würde das tbh erstmal so lassen, bis spring-data-elasticsearch eine neue version für die Verbindung zu elasticsearch-8 rausgebracht hat

2022-03-27 13:14 UTC, mor4thii approved these changes
Lgtm

2022-03-27 13:14 UTC, merged